### ISSUE TITLE
nochsstyle 并不能保留使用英文的标题样式。

### ISSUE THREAD

**Issue by yanshil** [Liam0205/sduthesis#8]
即便用了nochsstyle选项：`\documentclass[nochsstyle]{sduthesis}`, 由于是使用`ctexbook`, 也没有办法使得“目录”, “章节”等改为原有的content和chapter.

```
\ifSDU@opt@chsstyle
  \CTEXsetup[name={第,章}]{chapter}
  \CTEXsetup[number={\chinese{chapter}}]{chapter}
  \CTEXsetup[format={\centering}]{chapter}
  \CTEXsetup[nameformat={\bfseries\zihao{3}}]{chapter}
  \CTEXsetup[titleformat={\bfseries\zihao{3}}]{chapter}
  \CTEXsetup[aftername={\quad{}}]{chapter}
  \CTEXsetup[beforeskip={10pt}]{chapter}
  \CTEXsetup[afterskip={10pt}]{chapter}
  \CTEXsetup[name={$\S$\,,}]{section}
  \CTEXsetup[format={\bfseries\flushleft\zihao{4}}]{section}
  \CTEXsetup[format={\bfseries\flushleft\zihao{-4}}]{subsection}
  \CTEXsetup[format={\flushleft\zihao{-4}}]{subsubsection}
  \CTEXsetup[name={附录~}]{appendix}
  \CTEXsetup[number={\Alph{chapter}}]{appendix}
\else
  \PassOptionsToClass{nocap, noindent}{ctexbook}
```

据说`nocap`是使用英文格式？但是我并没有成功。。。。不知道是不是因为在overleaf上进行编译的问题

编译环境：  Overleaf, XeLaTeX

**Comment by Liam0205** [comment]
这是因为 `CTeX` 宏集更新，`nocap` 选项已经失效导致的问题。我来修复吧。

今晚给你一个简单的 workaround。

**Comment by yanshil** [comment]
哇！真是太感谢啦！回复太及时啦！
对啦我发现学校要求中英文目录。我暂时找到了个手动添加英文目录的方式。等我写完论文整理下思路大概会给你pull个request:D


Best regards，
Yanshi Luo


On Mar 22, 2017, at 7:01 PM, Liam Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


这是因为 CTeX 宏集更新，nocap 选项已经失效导致的问题。我来修复吧。

今晚给你一个简单的 workaround。

**Comment by Liam0205** [comment]
期待你的 PR。

你可以看到，[项目主页](http://liam0205.me/sduthesis/)提示这个项目正在寻找维护者。
如果你有兴趣，可以接手它吗——毕业多年，已经没有精力去维护它了。

**Comment by Liam0205** [comment]
一个可用的 workaround 可以是，将

```tex
\PassOptionsToClass{nocap, noindent}{ctexbook}
```

修改为

```tex
\PassOptionsToClass{scheme = plain, noindent}{ctexbook}
```
